[book]
authors = ["Dmitry Stepanov"]
language = "en"
multilingual = false
src = "src"
title = "Fyrox Book"
google_analytics_id = "G-ETGWNBR03Y"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/fyrox-book/fyrox-book.github.io"
git-repository-icon = "fa-github"

[output.html.fold]
enable = true
level = 7

